/*
Copyright (c) 2020 Mandelsoft. All rights reserved. This file is licensed under the Apache Software License, v. 2 except as noted otherwise in the LICENSE file

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"time"

	v1alpha1 "github.com/mandelsoft/kubipam/pkg/apis/ipam/v1alpha1"
	scheme "github.com/mandelsoft/kubipam/pkg/client/ipam/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// IPAMRangesGetter has a method to return a IPAMRangeInterface.
// A group's client should implement this interface.
type IPAMRangesGetter interface {
	IPAMRanges(namespace string) IPAMRangeInterface
}

// IPAMRangeInterface has methods to work with IPAMRange resources.
type IPAMRangeInterface interface {
	Create(*v1alpha1.IPAMRange) (*v1alpha1.IPAMRange, error)
	Update(*v1alpha1.IPAMRange) (*v1alpha1.IPAMRange, error)
	UpdateStatus(*v1alpha1.IPAMRange) (*v1alpha1.IPAMRange, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.IPAMRange, error)
	List(opts v1.ListOptions) (*v1alpha1.IPAMRangeList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.IPAMRange, err error)
	IPAMRangeExpansion
}

// iPAMRanges implements IPAMRangeInterface
type iPAMRanges struct {
	client rest.Interface
	ns     string
}

// newIPAMRanges returns a IPAMRanges
func newIPAMRanges(c *IpamV1alpha1Client, namespace string) *iPAMRanges {
	return &iPAMRanges{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the iPAMRange, and returns the corresponding iPAMRange object, and an error if there is any.
func (c *iPAMRanges) Get(name string, options v1.GetOptions) (result *v1alpha1.IPAMRange, err error) {
	result = &v1alpha1.IPAMRange{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("ipamranges").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of IPAMRanges that match those selectors.
func (c *iPAMRanges) List(opts v1.ListOptions) (result *v1alpha1.IPAMRangeList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.IPAMRangeList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("ipamranges").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested iPAMRanges.
func (c *iPAMRanges) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("ipamranges").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a iPAMRange and creates it.  Returns the server's representation of the iPAMRange, and an error, if there is any.
func (c *iPAMRanges) Create(iPAMRange *v1alpha1.IPAMRange) (result *v1alpha1.IPAMRange, err error) {
	result = &v1alpha1.IPAMRange{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("ipamranges").
		Body(iPAMRange).
		Do().
		Into(result)
	return
}

// Update takes the representation of a iPAMRange and updates it. Returns the server's representation of the iPAMRange, and an error, if there is any.
func (c *iPAMRanges) Update(iPAMRange *v1alpha1.IPAMRange) (result *v1alpha1.IPAMRange, err error) {
	result = &v1alpha1.IPAMRange{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("ipamranges").
		Name(iPAMRange.Name).
		Body(iPAMRange).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *iPAMRanges) UpdateStatus(iPAMRange *v1alpha1.IPAMRange) (result *v1alpha1.IPAMRange, err error) {
	result = &v1alpha1.IPAMRange{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("ipamranges").
		Name(iPAMRange.Name).
		SubResource("status").
		Body(iPAMRange).
		Do().
		Into(result)
	return
}

// Delete takes name of the iPAMRange and deletes it. Returns an error if one occurs.
func (c *iPAMRanges) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("ipamranges").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *iPAMRanges) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("ipamranges").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched iPAMRange.
func (c *iPAMRanges) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.IPAMRange, err error) {
	result = &v1alpha1.IPAMRange{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("ipamranges").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
