/*
Copyright (c) 2020 Mandelsoft. All rights reserved. This file is licensed under the Apache Software License, v. 2 except as noted otherwise in the LICENSE file

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/mandelsoft/kubipam/pkg/apis/ipam/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeIPAMRanges implements IPAMRangeInterface
type FakeIPAMRanges struct {
	Fake *FakeIpamV1alpha1
	ns   string
}

var ipamrangesResource = schema.GroupVersionResource{Group: "ipam.mandelsoft.org", Version: "v1alpha1", Resource: "ipamranges"}

var ipamrangesKind = schema.GroupVersionKind{Group: "ipam.mandelsoft.org", Version: "v1alpha1", Kind: "IPAMRange"}

// Get takes name of the iPAMRange, and returns the corresponding iPAMRange object, and an error if there is any.
func (c *FakeIPAMRanges) Get(name string, options v1.GetOptions) (result *v1alpha1.IPAMRange, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(ipamrangesResource, c.ns, name), &v1alpha1.IPAMRange{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.IPAMRange), err
}

// List takes label and field selectors, and returns the list of IPAMRanges that match those selectors.
func (c *FakeIPAMRanges) List(opts v1.ListOptions) (result *v1alpha1.IPAMRangeList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(ipamrangesResource, ipamrangesKind, c.ns, opts), &v1alpha1.IPAMRangeList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.IPAMRangeList{ListMeta: obj.(*v1alpha1.IPAMRangeList).ListMeta}
	for _, item := range obj.(*v1alpha1.IPAMRangeList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested iPAMRanges.
func (c *FakeIPAMRanges) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(ipamrangesResource, c.ns, opts))

}

// Create takes the representation of a iPAMRange and creates it.  Returns the server's representation of the iPAMRange, and an error, if there is any.
func (c *FakeIPAMRanges) Create(iPAMRange *v1alpha1.IPAMRange) (result *v1alpha1.IPAMRange, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(ipamrangesResource, c.ns, iPAMRange), &v1alpha1.IPAMRange{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.IPAMRange), err
}

// Update takes the representation of a iPAMRange and updates it. Returns the server's representation of the iPAMRange, and an error, if there is any.
func (c *FakeIPAMRanges) Update(iPAMRange *v1alpha1.IPAMRange) (result *v1alpha1.IPAMRange, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(ipamrangesResource, c.ns, iPAMRange), &v1alpha1.IPAMRange{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.IPAMRange), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeIPAMRanges) UpdateStatus(iPAMRange *v1alpha1.IPAMRange) (*v1alpha1.IPAMRange, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(ipamrangesResource, "status", c.ns, iPAMRange), &v1alpha1.IPAMRange{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.IPAMRange), err
}

// Delete takes name of the iPAMRange and deletes it. Returns an error if one occurs.
func (c *FakeIPAMRanges) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(ipamrangesResource, c.ns, name), &v1alpha1.IPAMRange{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeIPAMRanges) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(ipamrangesResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.IPAMRangeList{})
	return err
}

// Patch applies the patch and returns the patched iPAMRange.
func (c *FakeIPAMRanges) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.IPAMRange, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(ipamrangesResource, c.ns, name, pt, data, subresources...), &v1alpha1.IPAMRange{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.IPAMRange), err
}
