/*
Copyright (c) 2020 Mandelsoft. All rights reserved. This file is licensed under the Apache Software License, v. 2 except as noted otherwise in the LICENSE file

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	time "time"

	ipamv1alpha1 "github.com/mandelsoft/kubipam/pkg/apis/ipam/v1alpha1"
	versioned "github.com/mandelsoft/kubipam/pkg/client/ipam/clientset/versioned"
	internalinterfaces "github.com/mandelsoft/kubipam/pkg/client/ipam/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/mandelsoft/kubipam/pkg/client/ipam/listers/ipam/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// IPAMRangeInformer provides access to a shared informer and lister for
// IPAMRanges.
type IPAMRangeInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.IPAMRangeLister
}

type iPAMRangeInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewIPAMRangeInformer constructs a new informer for IPAMRange type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewIPAMRangeInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredIPAMRangeInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredIPAMRangeInformer constructs a new informer for IPAMRange type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredIPAMRangeInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.IpamV1alpha1().IPAMRanges(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.IpamV1alpha1().IPAMRanges(namespace).Watch(options)
			},
		},
		&ipamv1alpha1.IPAMRange{},
		resyncPeriod,
		indexers,
	)
}

func (f *iPAMRangeInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredIPAMRangeInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *iPAMRangeInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&ipamv1alpha1.IPAMRange{}, f.defaultInformer)
}

func (f *iPAMRangeInformer) Lister() v1alpha1.IPAMRangeLister {
	return v1alpha1.NewIPAMRangeLister(f.Informer().GetIndexer())
}
